package:
  name: magma-cuda111
  version: 2.5.2

source:
   url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-2.5.2.tar.gz
   patches:
     - cmakelists.patch
     - thread_queue.patch
     - cudaPointerAttributes.patch

build:
  number: 1
  script_env:
    - DESIRED_CUDA

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  license: BSD
  license_file: COPYRIGHT
