# Package to manage cuda version in PyTorch
# Please note: Build number should be advanced with
# every deployment. After the deployment to production
# use following links to validate the correctness of
# deployment:
# https://conda.anaconda.org/pytorch/noarch/
# https://conda.anaconda.org/pytorch/noarch/repodata.json
{% set build = 2 %}
{% set cuda_constraints=">=11.6,<11.7" %}
{% set libcufft_constraints=">=10.7.0.55,<10.7.2.50" %}
{% set libcublas_constraints=">=11.8.1.74,<11.10.1.25" %}
{% set libcusolver_constraints=">=11.3.2.55,<11.3.5.50" %}
{% set libcusparse_constraints=">=11.7.1.55,<11.7.3.50" %}
{% set libnpp_constraints=">=11.6.0.55,<11.7.3.21" %}
{% set libnvjpeg_constraints=">=11.6.0.55,<11.7.2.34" %}
{% if version == '11.7' %}
{% set cuda_constraints=">=11.7,<11.8" %}
{% set libcufft_constraints=">=10.7.2.50,<10.9.0.58" %}
{% set libcublas_constraints=">=11.10.1.25,<11.11.3.6" %}
{% set libcusolver_constraints=">=11.3.5.50,<11.4.1.48" %}
{% set libcusparse_constraints=">=11.7.3.50,<11.7.5.86" %}
{% set libnpp_constraints=">=11.7.3.21,<11.8.0.86" %}
{% set libnvjpeg_constraints=">=11.7.2.34,<11.9.0.86" %}
{% elif version == '11.8' %}
{% set cuda_constraints=">=11.8,<12.0" %}
{% set libcufft_constraints=">=10.9.0.58,<11.0.0.21" %}
{% set libcublas_constraints=">=11.11.3.6,<12.0.1.189" %}
{% set libcusolver_constraints=">=11.4.1.48,<11.4.2.57" %}
{% set libcusparse_constraints=">=11.7.5.86,<12.0.0.76" %}
{% set libnpp_constraints=">=11.8.0.86,<12.0.0.30" %}
{% set libnvjpeg_constraints=">=11.9.0.86,<12.0.0.28" %}
{% endif %}

package:
  name: pytorch-cuda
  version: {{ version }}
build:
  number: {{ build }}
  noarch: generic
requirements:
  run:
    - cuda={{ version }}
  run_constrained:
    - cuda-cccl {{ cuda_constraints }}
    - cuda-command-line-tools {{ cuda_constraints }}
    - cuda-compiler {{ cuda_constraints }}
    - cuda-cudart {{ cuda_constraints }}
    - cuda-cudart-dev {{ cuda_constraints }}
    - cuda-cuobjdump {{ cuda_constraints }}
    - cuda-cupti {{ cuda_constraints }}
    - cuda-cuxxfilt {{ cuda_constraints }}
    - cuda-libraries {{ cuda_constraints }}
    - cuda-nvcc {{ cuda_constraints }}
    - cuda-nvprune {{ cuda_constraints }}
    - cuda-nvrtc {{ cuda_constraints }}
    - cuda-nvtx {{ cuda_constraints }}
    - cuda-runtime {{ cuda_constraints }}
    - cuda-toolkit {{ cuda_constraints }}
    - cuda-tools {{ cuda_constraints }}
    - libcufft {{ libcufft_constraints }}
    - libcublas {{ libcublas_constraints }}
    - libcusolver {{ libcusolver_constraints }}
    - libcusparse {{ libcusparse_constraints }}
    - libnpp {{ libnpp_constraints }}
    - libnvjpeg {{ libnvjpeg_constraints }}
  # None, pytorch should depend on pytorch-cuda
test:
  commands:
    - echo "pytorch-cuda metapackage is created."
about:
  summary: Metapackage to select the PyTorch variant. Use conda's pinning mechanism in your environment to control which variant you want.
