parameters:
  package: ''
  spec: ''
  jobDesc: ''
  packageDesc: ''
  msagent: true
  cpuEnabled: true
  cudaEnabled: true
  condaEnabled: true
  wheelsEnabled: true
  override: false

jobs:
- job: 'Windows_${{ parameters.spec }}_${{ parameters.package }}_Build'
  timeoutInMinutes: 180
  cancelTimeoutInMinutes: 5
  condition: > 
    or(and(eq('${{ parameters.package }}', 'Conda'), eq('${{ parameters.spec }}', 'CPU'),
           eq('${{ parameters.condaEnabled }}', 'true'), eq('${{ parameters.cpuEnabled }}', 'true')),
       and(eq('${{ parameters.package }}', 'Wheels'), eq('${{ parameters.spec }}', 'CPU'),
           eq('${{ parameters.wheelsEnabled }}', 'true'), eq('${{ parameters.cpuEnabled }}', 'true')),
       and(eq('${{ parameters.package }}', 'Conda'), eq('${{ parameters.spec }}', 'CUDA'),
           eq('${{ parameters.condaEnabled }}', 'true'), eq('${{ parameters.cudaEnabled }}', 'true')),
       and(eq('${{ parameters.package }}', 'Wheels'), eq('${{ parameters.spec }}', 'CUDA'),
           eq('${{ parameters.wheelsEnabled }}', 'true'), eq('${{ parameters.cudaEnabled }}', 'true')))
  variables:
    - ${{ if eq(parameters.override, 'true') }}:
      - name: PYTORCH_BUILD_VERSION
        value: '1.1.0'
      - name: PYTORCH_BUILD_NUMBER
        value: 1
      - name: PYTORCH_REPO
        value: 'pytorch'
      - name: PYTORCH_BRANCH
        value: 'v1.1.0'
      - name: TORCH_CONDA_BUILD_FOLDER
        value: 'pytorch-1.1.0'
    - ${{ if eq(parameters.msagent, 'true') }}:
      - name: USE_SCCACHE
        value: 0
    - ${{ if eq(parameters.msagent, 'false') }}:
      - name: USE_SCCACHE
        value: 1
    - ${{ if eq(parameters.package, 'Conda') }}:
      - group: peterjc_anaconda_token
      - name: PYTORCH_FINAL_PACKAGE_DIR
        value: '$(Build.Repository.LocalPath)\windows\output'
      
  strategy:
    maxParallel: 10
    matrix:
      ${{ if eq(parameters.spec, 'CPU') }}:
        PY3.5:
          DESIRED_PYTHON: 3.5
          CUDA_VERSION: cpu
        PY3.6:
          DESIRED_PYTHON: 3.6
          CUDA_VERSION: cpu
        PY3.7:
          DESIRED_PYTHON: 3.7
          CUDA_VERSION: cpu
      ${{ if and(eq(parameters.package, 'Wheels'), eq(parameters.spec, 'CPU')) }}:
        LIBTORCH:
          DESIRED_PYTHON: 3
          CUDA_VERSION: cpu
          BUILD_PYTHONLESS: 1
        LIBTORCH_DEBUG:
          DESIRED_PYTHON: 3
          CUDA_VERSION: cpu
          BUILD_PYTHONLESS: 1
          DEBUG: 1
      ${{ if ne(parameters.spec, 'CPU') }}:
        PY3.5_90:
          DESIRED_PYTHON: 3.5
          CUDA_VERSION: 90
        PY3.6_90:
          DESIRED_PYTHON: 3.6
          CUDA_VERSION: 90
        PY3.7_90:
          DESIRED_PYTHON: 3.7
          CUDA_VERSION: 90
        PY3.5_100:
          DESIRED_PYTHON: 3.5
          CUDA_VERSION: 100
        PY3.6_100:
          DESIRED_PYTHON: 3.6
          CUDA_VERSION: 100
        PY3.7_100:
          DESIRED_PYTHON: 3.7
          CUDA_VERSION: 100
      ${{ if and(ne(parameters.spec, 'CPU'), eq(parameters.package, 'Wheels')) }}:
        LIBTORCH_90:
          DESIRED_PYTHON: 3
          BUILD_PYTHONLESS: 1
          CUDA_VERSION: 90
        LIBTORCH_90_DEBUG:
          DESIRED_PYTHON: 3
          BUILD_PYTHONLESS: 1
          CUDA_VERSION: 90
          DEBUG: 1
        LIBTORCH_100:
          DESIRED_PYTHON: 3
          BUILD_PYTHONLESS: 1
          CUDA_VERSION: 100
        LIBTORCH_100_DEBUG:
          DESIRED_PYTHON: 3
          BUILD_PYTHONLESS: 1
          CUDA_VERSION: 100
          DEBUG: 1

  pool:
    ${{ if eq(parameters.msagent, 'true') }}:
      vmImage: 'win1803'
    ${{ if eq(parameters.msagent, 'false') }}:
      name: 'release'

  steps:
  - checkout: self
    clean: true

  - template: setup_env_for_msagent.yml
    parameters:
      msagent: ${{ parameters.msagent }}

  - template: setup_nightly_variables.yml

  - ${{ if eq(parameters.package, 'Wheels') }}:
    - template: build_wheels.yml
      parameters:
        msagent: ${{ parameters.msagent }}

  - ${{ if eq(parameters.package, 'Conda') }}:
    - template: build_conda.yml
      parameters:
        msagent: ${{ parameters.msagent }}

  - ${{ if or(eq(parameters.package, 'Wheels'), eq(parameters.package, 'Conda')) }}:
    - template: publish_test_results.yml
      parameters:
        msagent: ${{ parameters.msagent }}

  - ${{ if and(eq(parameters.package, 'Wheels'), eq(parameters.spec, 'CPU')) }}:
    - template: upload_to_s3.yml
      parameters:
        cuVer: '$(CUDA_VERSION)'
        cudaVer: '$(CUDA_VERSION)'

  - ${{ if and(eq(parameters.package, 'Wheels'), ne(parameters.spec, 'CPU')) }}:
    - template: upload_to_s3.yml
      parameters:
        cuVer: 'cu$(CUDA_VERSION)'
        cudaVer: 'cuda$(CUDA_VERSION)'

  - ${{ if eq(parameters.package, 'Conda') }}:
    - template: upload_to_conda.yml
      parameters:
        user: $(peterjc_conda_username)
        pass: $(peterjc_conda_password)

  # If you want to upload binaries to Azure Git, please uncomment this section.
  # - ${{ if or(eq(parameters.package, 'Wheels'), eq(parameters.package, 'Conda')) }}:
  #   - template: publish_test_results.yml
  #     parameters:
  #       msagent: ${{ parameters.msagent }}
  #   - template: publish_packages.yml
  #     parameters:
  #       package: ${{ parameters.package }}
