package:
  name: torchvision-cpu
  version: 0.2.1

source:
 git_rev: v0.2.1
 git_url: https://github.com/pytorch/vision.git
   

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pillow >=4.1.1
    - numpy >=1.11
    - pytorch-cpu >=0.4
    - six

build:
  number: 2
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

test:
   imports:
      - torchvision
      - torchvision.datasets
      - torchvision.transforms

about:
  home: https://github.com/pytorch/vision
  license: BSD
  license_file: LICENSE
  summary: 'image and video datasets and models for torch deep learning'
