[tool.ruff]
target-version = "py38"
line-length = 120
ignore = [
    "PERF401",
]
select = [
    "B",
    "C4",
    "G",
    "E",
    "F",
    "SIM1",
    "W",
    # Not included in flake8
    "UP",
    "PERF",
    "PGH004",
    "PIE807",
    "PIE810",
    "PLE",
    "PLR1722", # use sys exit
    "PLW3301", # nested min max
    "RUF017",
    "TRY302",
]
