package:
  name: faiss-cpu
  version: "{{ environ.get('FAISS_BUILD_VERSION') }}"

source:
  path: ../faiss-src

requirements:
  build:
    - python
    - numpy 1.11.*
    - gcc
    - setuptools
    - swig
    - mkl

  run:
    - python
    - libgcc
    - numpy >=1.11
    - mkl

build:
  number: {{ environ.get('FAISS_BUILD_NUMBER') }}
  string: py{{py}}_cuda{{ environ['CUDA_VERSION'] }}_{{ environ.get('FAISS_BUILD_NUMBER') }}

test:
 imports:
    - faiss
 source_files:
   - tests
 commands:
   - python tests/test_index.py
   - python tests/test_index_composite.py

about:
  home: https://github.com/facebookresearch/faiss
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.
