package:
  name: "{{ environ.get('PACKAGE_NAME') }}"
  version: 2.6.1

source:
   url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-2.6.1.tar.gz
   patches:
     - cmakelists.patch
     - thread_queue.patch

build:
  number: 0
  script_env:
    - DESIRED_CUDA
    - CUDA_ARCH_LIST

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  license: BSD
  license_file: COPYRIGHT
