package:
  name: "{{ environ.get('PACKAGE_NAME') }}"
  version: 2.6.1

source:
   url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-2.6.1.tar.gz
   patches:
     - cmakelists.patch
     - thread_queue.patch
     - getrf_shfl.patch  # incorrect results for <7.0 arch
     - getrf_nbparam.patch  # fixes "too many resources requested for launch" error
     - CMake.patch # removes fermi for CUDA12+

build:
  number: 1
  script_env:
    - DESIRED_CUDA
    - CUDA_ARCH_LIST

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  license: BSD
  license_file: COPYRIGHT
