package:
  name: magma-cuda102
  version: 2.5.1

source:
   url: http://icl.utk.edu/projectsfiles/magma/downloads/magma-2.5.1.tar.gz
   patches:
     - cmakelists.patch
     - thread_queue.patch

build:
  number: 1

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  license: BSD
  license_file: COPYRIGHT
