#!/usr/bin/env bash

# Make sure to update these versions when doing a release first
PYTORCH_VERSION=${PYTORCH_VERSION:-1.12.0}
TORCHVISION_VERSION=${TORCHVISION_VERSION:-0.13.0}
TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION:-0.12.0}
TORCHTEXT_VERSION=${TORCHTEXT_VERSION:-0.13.0}
