#!/usr/bin/env bash

# Make sure to update these versions when doing a release first
PYTORCH_VERSION=${PYTORCH_VERSION:-2.2.0}
TORCHVISION_VERSION=${TORCHVISION_VERSION:-0.17.0}
TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION:-2.2.0}
TORCHTEXT_VERSION=${TORCHTEXT_VERSION:-0.17.0}
TORCHDATA_VERSION=${TORCHDATA_VERSION:-0.7.1}
TORCHREC_VERSION=${TORCHREC_VERSION:-0.6.0}
FBGEMMGPU_VERSION=${FBGEMMGPU_VERSION:-0.6.0}
