#!/usr/bin/env bash

# Make sure to update these versions when doing a release first
PYTORCH_VERSION=${PYTORCH_VERSION:-1.13.1}
TORCHVISION_VERSION=${TORCHVISION_VERSION:-0.14.1}
TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION:-0.13.1}
TORCHTEXT_VERSION=${TORCHTEXT_VERSION:-0.14.1}
