package:
  name: magma-cuda75
  version: 2.1.0

source:
   url: http://icl.cs.utk.edu/projectsfiles/magma/downloads/magma-2.1.0.tar.gz
   patches:
     - cmakelists.patch
     - thread_queue.patch

build:
  number: 5

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  license: BSD
  license_file: COPYRIGHT