{% set vcver="14.1" %}
{% set vcfeature="14" %}
{% set vsyear="2017" %}
{% set fullver="15.4.27004.2010" %}

package:
  name: vs{{ vsyear }}
  version: {{ fullver }}

build:
  skip: True  [not win]

outputs:
  - name: vs{{ vsyear }}_{{ cross_compiler_target_platform }}
    script: install_activate.bat
    track_features:
      # VS 2017 is binary-compatible with VS 2015/vc14.  Tools are "v141".
      strong:
        - vc{{ vcfeature }}
    run_exports:
      - vc {{ vcver }}
    about:
      summary: Activation and version verification of MSVC {{ vcver }} (VS {{ vsyear }}) compiler
      license: BSD 3-clause
  - name: vs{{ vsyear }}_runtime
    script: install_runtime.bat
  - name: vc
    version: {{ vcver }}
    track_features:
      - vc{{ vcfeature }}
    requirements:
      run:
        - {{ pin_subpackage('vs' ~ vsyear ~ '_runtime') }}
    about:
      home: https://github.com/conda/conda/wiki/VC-features
      license: Modified BSD License (3-clause)
      license_family: BSD
      summary: A meta-package to track VC features.
      description: |
          This metapackage is used to activate vc features without
          depending on Python.
      doc_url: https://github.com/conda/conda/wiki/VC-features
      dev_url: https://github.com/conda/conda/wiki/VC-features
