{% set vcver="14.1" %}
{% set vcfeature="14" %}
{% set vsyear="2017" %}
{% set fullver="15.4.27004.2010" %}

package:
  name: vs{{ vsyear }}
  version: {{ fullver }}

build:
  skip: True  [not win]
  script_env:
    - VSDEVCMD_ARGS # [win]

outputs:
  - name: vs{{ vsyear }}_{{ cross_compiler_target_platform }}
    script: install_activate.bat
    track_features:
      # VS 2017 is binary-compatible with VS 2015/vc14.  Tools are "v141".
      strong:
        - vc{{ vcfeature }}
    about:
      summary: Activation and version verification of MSVC {{ vcver }} (VS {{ vsyear }}) compiler
      license: BSD 3-clause
