name: build-macos-arm64-domains-wheels

on:
  push:
    branches:
      main
    paths:
      - .github/workflows/build-macos-arm64-domains-wheels.yml
  pull_request:
    paths:
      - .github/workflows/build-macos-arm64-domains-wheels.yml

# For setup-miniconda, see https://github.com/conda-incubator/setup-miniconda/issues/179
defaults:
  run:
    shell: bash -x -e -l {0}

env:
  # Needed for conda builds
  ALPINE_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine"
  ANACONDA_USER: pytorch
  AWS_DEFAULT_REGION: us-east-1
  BUILD_ENVIRONMENT: build-macos-arm64-domains-wheels
  IN_CI: 1
  IS_GHA: 1
  SKIP_ALL_TESTS: 1
  CROSS_COMPILE_ARM64: 1

jobs:
  build-linux-magma:
    runs-on: macos-m1-11
    steps:
      - name: Checkout PyTorch builder
        uses: actions/checkout@v2
      - name: Checkout pytorch/vision
        uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
        with:
          ref: main
          submodules: recursive
          repository: pytorch/vision
          path: vision
      - name: Build M1 domains
        run: |
          ./build_m1_domains.sh
