name: Validate MacOS Binaries

on:
  pull_request:
    paths:
      - .github/workflows/call-reusable-workflow-to-validate-MacOS-binaries.yml


jobs:
  generate-ARM64-conda-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: conda
      os: macos-arm64
      channel: all

  validate-MacOS-ARM64-conda-packages:
    needs: generate-ARM64-conda-matrix 
    uses: ./.github/workflows/validate-MacOS-binaries.yml
    name: validate MacOS-ARM64-conda
    with: 
      test-matrix: ${{ needs.generate-ARM64-conda-matrix.outputs.matrix }}
