name: Test check_binary

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/test-check-binary.yml
      - check_binary.sh
      - test/smoke_test/smoke_test.py

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  check_binary_linux_cpu:
    name: Test check_binary.sh for Linux CPU
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      repository: "pytorch/builder"
      docker-image: python:3.11
      script: |
          pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
          DESIRED_PYTHON=3.11 DESIRED_CUDA=cpu PACKAGE_TYPE=manywheel ./check_binary.sh

  check_binary_linux_cuda:
    name: Test check_binary.sh for Linux CUDA
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      repository: "pytorch/builder"
      runner: linux.4xlarge.nvidia.gpu
      docker-image: python:3.11
      script: |
          pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu121
          DESIRED_PYTHON=3.11 DESIRED_CUDA=cu121 PACKAGE_TYPE=manywheel ./check_binary.sh
