name: Test check_binary

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/test-check-binary.yml
      - check_binary.sh
      - test/smoke_test/smoke_test.py

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  check_binary:
    name: Test check binary

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install latest nightly
        run: |
          pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
      - name: Run check_binary.sh
        run: |
          set +e
          DESIRED_PYTHON=3.11 DESIRED_CUDA=cpu PACKAGE_TYPE=manywheel ./check_binary.sh 
