name: Validate release binaries (all OS)

on:
  schedule:
    # At 3 am and 2 pm UTC (7 am and 8 pm PDT)
    - cron: "0 3,14 * * *"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:
  push:
    branches:
      main
    paths:
      - .github/workflows/validate-release-binaries.yml
      - .github/workflows/validate-linux-binaries.yml
      - .github/workflows/validate-windows-binaries.yml
      - .github/workflows/validate-macos-binaries.yml
      - .test/smoke_test/*
  pull_request:
    paths:
      - .github/workflows/validate-release-binaries.yml
      - .github/workflows/validate-linux-binaries.yml
      - .github/workflows/validate-windows-binaries.yml
      - .github/workflows/validate-macos-binaries.yml
      - .test/smoke_test/*

jobs:
  validate-release-binaries:
    uses: ./.github/workflows/validate-binaries.yml
    with:
      channel: release
      os: all
