name: Validate MacOS Binaries

on:
  workflow_call:
    inputs:
      channel:
        description: "Channel to use (nightly, test, release, all)"
        required: true
        type: string
      ref:
        description: 'Reference to checkout, defaults to empty'
        default: ""
        required: false
        type: string
      torchonly:
        description: 'Validate torchonly'
        default: false
        required: false
        type: boolean
      version:
        description: 'Version to validate - optional'
        default: ""
        required: false
        type: string
      release-matrix:
        description: 'Release matrix - optional'
        default: ""
        required: false
        type: string
      use-only-dl-pytorch-org:
        description: 'Use only download.pytorch.org when generating wheel install command'
        default: false
        required: false
        type: boolean
  workflow_dispatch:
    inputs:
      channel:
        description: "Channel to use (nightly, test, release, all)"
        required: true
        type: choice
        options:
          - release
          - nightly
          - test
          - all
      ref:
        description: 'Reference to checkout, defaults to empty'
        default: ""
        required: false
        type: string
      torchonly:
        description: 'Validate torchonly'
        default: false
        required: false
        type: boolean
      version:
        description: 'Version to validate - optional'
        default: ""
        required: false
        type: string
      release-matrix:
        description: 'Release matrix - optional'
        default: ""
        required: false
        type: string
      use-only-dl-pytorch-org:
        description: 'Use only download.pytorch.org when generating wheel install command'
        default: false
        required: false
        type: boolean

jobs:
  generate-macos-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: all
      os: macos
      channel: ${{ inputs.channel }}
      use-only-dl-pytorch-org: ${{ inputs.use-only-dl-pytorch-org }}

  macos:
    needs: generate-macos-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-macos-matrix.outputs.matrix) }}
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
    name: ${{ matrix.build_name }}
    with:
      runner: ${{ matrix.validation_runner }}
      repository: "pytorch/builder"
      ref: ${{ inputs.ref || github.ref }}
      job-name: ${{ matrix.build_name }}
      binary-matrix: ${{ toJSON(matrix) }}
      script: |
        set -ex
        export ENV_NAME="conda-env-${{ github.run_id }}"
        export TARGET_OS="macos"
        export TORCH_ONLY=${{ inputs.torchonly }}
        export RELEASE_VERSION=${{ inputs.version }}
        printf '%s\n' ${{ toJson(inputs.release-matrix) }} > release_matrix.json
        source ./.github/scripts/validate_binaries.sh
